apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21001

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: key
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: actv
    port: 21
    targetPort: 21
  - name: pasv
    port: 21001
    targetPort: 21001
