apiVersion: 1

datasources:
- name: telegraf
  type: influxdb
  access: proxy
  url: http://influxdb_container:8086
  isDefault: true
  editable: true
  database: telegraf
  jsonData:
   timeInterval: '5s'